version: 2.1

orbs:
  yarn: artsy/yarn@3.0.0

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/lint:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/test:
          requires:
            - yarn/workflow-queue
      - yarn/run:
          name: visual-test
          script: visual-test
          requires:
            - yarn/workflow-queue
          filters:
            branches:
              ignore: master
      - yarn/run:
          name: visual-test-master
          script: visual-test --auto-accept-changes
          requires:
            - yarn/workflow-queue
          filters:
            branches:
              only: master
      - yarn/auto-release:
          # The deploy job is the _only_ job that should have access to our npm
          # tokens. We include a context that has our publish credentials
          # explicitly in this step. https://circleci.com/docs/2.0/contexts/
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - yarn/test
            - yarn/lint
            - yarn/type-check
            - yarn/update-cache
      - yarn/run:
          name: deploy-docs
          script: deploy-docs
          context: hokusai
          requires:
            - yarn/auto-release
          filters:
            branches:
              only: master
